### ISSUE TITLE
Repository website link is broken

### ISSUE THREAD

**Issue by Eldemarkki** [Testausserveri/matikkaeditori.fi#54]
This link leads to a page that doesn't exist anymore. We should change it to [matikkaeditori.fi](https://matikkaeditori.fi/) and the DNS record should be deleted.

![image](https://github.com/Testausserveri/matikkaeditori.fi-v3/assets/38920928/df56c9b9-1eeb-47a0-8a35-5a95584a7985)
![image](https://github.com/Testausserveri/matikkaeditori.fi-v3/assets/38920928/fa6eab8f-f2f6-4a07-ba65-7457ae784af2)

**Comment by Esinko** [comment]
Has been fixed.
